In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from datetime import datetime
import sklearn

In [2]:
data = pd.read_csv(r'/Users/maximvasilev/Desktop/ML/about_stations.csv')
data

,Unnamed: 0,Line,English name,Russian name,Coordinates,Arts & Entertainment,College & University,Event,Food,Nightlife Spot,Outdoors & Recreation,Professional & Other Places,Residence,Shop & Service,Travel & Transport
0,0,1,Bulvar Rokossovskogo,Бульвар Рокоссовского,"55.8148,37.7342",5,8,0,11,6,9,46,6,55,9
1,1,1,Cherkizovskaya,Черкизовская,"55.8038,37.7448",5,25,0,12,4,19,38,7,36,10
2,2,1,Preobrazhenskaya Ploshchad,Преображенская площадь,"55.7963,37.7151",13,26,0,31,5,31,110,21,81,14
3,3,1,Sokolniki,Сокольники,"55.7888,37.6802",16,20,0,56,13,43,90,27,81,18
4,4,1,Krasnoselskaya,Красносельская,"55.7801,37.6673",31,25,0,107,28,25,134,23,91,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,259,14,Likhobory,Лихоборы,"55.8472,37.5513",5,15,0,8,3,9,32,12,26,10
260,260,15,Kosino,Косино,"55.7033,37.8511",3,6,0,15,6,10,40,14,54,10
261,261,15,Ulitsa Dmitriyevskogo,Улица Дмитриевского,"55.7100,37.8792",3,4,0,9,5,11,20,17,28,3
262,262,15,Lukhmanovskaya,Лухмановская,"55.7085,37.9004",10,4,0,6,5,9,25,17,21,3
263,263,15,Nekrasovka,Некрасовка,"55.7036,37.9264",1,1,0,7,3,5,7,11,18,4

In [4]:
from sklearn.preprocessing import MinMaxScaler

In [5]:
data_new = data[["Arts & Entertainment", "College & University", "Event",
                "Food", "Nightlife Spot", "Outdoors & Recreation", "Professional & Other Places", "Residence",
               "Shop & Service", "Travel & Transport"]]

In [6]:
min_max_scaler = MinMaxScaler()
min_max_scaler

MinMaxScaler()

In [7]:
min_max_scaler = min_max_scaler.fit(data_new[["Arts & Entertainment", "College & University", "Event",
                "Food", "Nightlife Spot", "Outdoors & Recreation", "Professional & Other Places", "Residence",
               "Shop & Service", "Travel & Transport"]])

min_max_scaler = min_max_scaler.transform(data_new[["Arts & Entertainment", "College & University", "Event",
                "Food", "Nightlife Spot", "Outdoors & Recreation", "Professional & Other Places", "Residence",
               "Shop & Service", "Travel & Transport"]])
min_max_scaler

array([[0.03816794, 0.07291667, 0.        , ..., 0.08333333, 0.27135678,
        0.06521739],
       [0.03816794, 0.25      , 0.        , ..., 0.09722222, 0.1758794 ,
        0.07608696],
       [0.09923664, 0.26041667, 0.        , ..., 0.29166667, 0.40201005,
        0.11956522],
       ...,
       [0.02290076, 0.03125   , 0.        , ..., 0.23611111, 0.13567839,
        0.        ],
       [0.07633588, 0.03125   , 0.        , ..., 0.23611111, 0.10050251,
        0.        ],
       [0.00763359, 0.        , 0.        , ..., 0.15277778, 0.08542714,
        0.01086957]])

In [8]:
data_mod = data.copy()

In [9]:
data_mod[["Arts & Entertainment", "College & University", "Event",
                "Food", "Nightlife Spot", "Outdoors & Recreation", "Professional & Other Places", "Residence",
               "Shop & Service", "Travel & Transport"]] = min_max_scaler

In [10]:
data_mod.head

<bound method NDFrame.head of      Unnamed: 0 Line                English name            Russian name  \
0             0    1        Bulvar Rokossovskogo   Бульвар Рокоссовского
1             1    1              Cherkizovskaya            Черкизовская
2             2    1  Preobrazhenskaya Ploshchad  Преображенская площадь
3             3    1                   Sokolniki              Сокольники
4             4    1              Krasnoselskaya          Красносельская
..          ...  ...                         ...                     ...
259         259   14                   Likhobory                Лихоборы
260         260   15                      Kosino                  Косино
261         261   15       Ulitsa Dmitriyevskogo     Улица Дмитриевского
262         262   15              Lukhmanovskaya            Лухмановская
263         263   15                  Nekrasovka              Некрасовка

         Coordinates  Arts & Entertainment  College & University  Event  \
0    55.8148,37.7342              0.038168              0.072917    0.0
1    55.8038,37.7448              0.038168              0.250000    0.0
2    55.7963,37.7151              0.099237              0.260417    0.0
3    55.7888,37.6802              0.122137              0.197917    0.0
4    55.7801,37.6673              0.236641              0.250000    0.0
..               ...                   ...                   ...    ...
259  55.8472,37.5513              0.038168              0.145833    0.0
260  55.7033,37.8511              0.022901              0.052083    0.0
261  55.7100,37.8792              0.022901              0.031250    0.0
262  55.7085,37.9004              0.076336              0.031250    0.0
263  55.7036,37.9264              0.007634              0.000000    0.0

         Food  Nightlife Spot  Outdoors & Recreation  \
0    0.033195        0.039735               0.089888
1    0.037344        0.026490               0.202247
2    0.116183        0.033113               0.337079
3    0.219917        0.086093               0.471910
4    0.431535        0.185430               0.269663
..        ...             ...                    ...
259  0.020747        0.019868               0.089888
260  0.049793        0.039735               0.101124
261  0.024896        0.033113               0.112360
262  0.012448        0.033113               0.089888
263  0.016598        0.019868               0.044944

     Professional & Other Places  Residence  Shop & Service  \
0                       0.239583   0.083333        0.271357
1                       0.197917   0.097222        0.175879
2                       0.572917   0.291667        0.402010
3                       0.468750   0.375000        0.402010
4                       0.697917   0.319444        0.452261
..                           ...        ...             ...
259                     0.166667   0.166667        0.125628
260                     0.208333   0.194444        0.266332
261                     0.104167   0.236111        0.135678
262                     0.130208   0.236111        0.100503
263                     0.036458   0.152778        0.085427

     Travel & Transport
0              0.065217
1              0.076087
2              0.119565
3              0.163043
4              0.728261
..                  ...
259            0.076087
260            0.076087
261            0.000000
262            0.000000
263            0.010870

[264 rows x 15 columns]>

In [11]:
data_mod.pop("Event")
data_mod

,Unnamed: 0,Line,English name,Russian name,Coordinates,Arts & Entertainment,College & University,Food,Nightlife Spot,Outdoors & Recreation,Professional & Other Places,Residence,Shop & Service,Travel & Transport
0,0,1,Bulvar Rokossovskogo,Бульвар Рокоссовского,"55.8148,37.7342",0.038168,0.072917,0.033195,0.039735,0.089888,0.239583,0.083333,0.271357,0.065217
1,1,1,Cherkizovskaya,Черкизовская,"55.8038,37.7448",0.038168,0.250000,0.037344,0.026490,0.202247,0.197917,0.097222,0.175879,0.076087
2,2,1,Preobrazhenskaya Ploshchad,Преображенская площадь,"55.7963,37.7151",0.099237,0.260417,0.116183,0.033113,0.337079,0.572917,0.291667,0.402010,0.119565
3,3,1,Sokolniki,Сокольники,"55.7888,37.6802",0.122137,0.197917,0.219917,0.086093,0.471910,0.468750,0.375000,0.402010,0.163043
4,4,1,Krasnoselskaya,Красносельская,"55.7801,37.6673",0.236641,0.250000,0.431535,0.185430,0.269663,0.697917,0.319444,0.452261,0.728261
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,259,14,Likhobory,Лихоборы,"55.8472,37.5513",0.038168,0.145833,0.020747,0.019868,0.089888,0.166667,0.166667,0.125628,0.076087
260,260,15,Kosino,Косино,"55.7033,37.8511",0.022901,0.052083,0.049793,0.039735,0.101124,0.208333,0.194444,0.266332,0.076087
261,261,15,Ulitsa Dmitriyevskogo,Улица Дмитриевского,"55.7100,37.8792",0.022901,0.031250,0.024896,0.033113,0.112360,0.104167,0.236111,0.135678,0.000000
262,262,15,Lukhmanovskaya,Лухмановская,"55.7085,37.9004",0.076336,0.031250,0.012448,0.033113,0.089888,0.130208,0.236111,0.100503,0.000000
263,263,15,Nekrasovka,Некрасовка,"55.7036,37.9264",0.007634,0.000000,0.016598,0.019868,0.044944,0.036458,0.152778,0.085427,0.010870

In [13]:
data_mod.to_csv("additional_info_for_stations.csv", sep = ",")

In [38]:
data_mod.describe()

,Unnamed: 0,Arts & Entertainment,College & University,Food,Nightlife Spot,Outdoors & Recreation,Professional & Other Places,Residence,Shop & Service,Travel & Transport
count,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000
mean,131.500000,0.169009,0.279119,0.215296,0.125978,0.346229,0.459182,0.337489,0.400430,0.241313
std,76.354437,0.225298,0.248526,0.200737,0.183383,0.229922,0.254110,0.187550,0.200049,0.242170
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,65.750000,0.030534,0.083333,0.078838,0.033113,0.168539,0.260417,0.194444,0.265075,0.086957
50%,131.500000,0.061069,0.171875,0.141079,0.052980,0.292135,0.367188,0.333333,0.371859,0.141304
75%,197.250000,0.208015,0.437500,0.282158,0.127483,0.483146,0.697917,0.458333,0.523869,0.328804
max,263.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [36]:
a = pd.DataFrame([[1,2,3], [4,5,6], [7,8,9]], columns = ["a", "b", "c"])
a
a["r"] = [1, 2, 3]
a
print(a.loc[a["b"] == 5]["a"].values[0])
print("---")
print(a)

4
---
   a  b  c  r
0  1  2  3  1
1  4  5  6  2
2  7  8  9  3